### ISSUE TITLE
Ctrl+M does not work?

### ISSUE THREAD

**Issue by tdalon** [bulkan/shortcuts-for-trello#1]
Hi
while hovering on the card and trying Ctrl+M nothing happens as expected.
I am using Windows 7 and Chrome 37.0 (Dev Channel).

**Comment by bulkan** [comment]
That's weird. Which operating system are you using ?

**Comment by wildeyes** [comment]
I am getting this:
`Refused to frame 'https://d3ijcis4e2ziok.cloudfront.net/tpc-check.html' because it violates the following Content Security Policy directive: "frame-src 'self' render.githubusercontent.com www.youtube.com checkout.paypal.com".`

**Comment by tonytamps** [comment]
I just did a little test. Ctrl+M worked for me on Chrome (OSX), but only when DevTools was _not_ open.
I also saw a similar error in my console when I opened it. I don't think its related?

Got any details about browser or OS for me?

**Comment by bulkan** [comment]
@wildeyes that error is **not** from this extension. @tonytamps is right, Ctrl+m (while hovering over a card) works for us on OSX.

**Comment by wildeyes** [comment]
Windows 8 + Chrome Version 36.0.1985.125 m

**Comment by tonytamps** [comment]
This and Ctrl+U appear to be broken on Chrome (WIndows 8).
I'll work on this when I can and let you know.

**Comment by pronobis** [comment]
Broken also on Ubuntu 12.10 + Chrome 39

**Comment by tonytamps** [comment]
I'm working on a more permanent solution to the greater problem of shortcuts cross-operating systems.
Chrome recently introduced a way to make this happen so I'm moving all the code to that approach.

**Comment by pronobis** [comment]
Great! Looking forward to the updates!

**Comment by bulkan** [comment]
Fixed in #2 to @tonytamps awesome work.

**Comment by bulkan** [comment]
I've published a version with these changes. You should be able to create your own shortcuts. 

![image](https://cloud.githubusercontent.com/assets/13985/4184146/08235f6c-3746-11e4-89bc-fe6dc81eceea.png)

**Comment by pronobis** [comment]
Just confirming that it works great now!
