### ISSUE TITLE
Scroll to bottom of list not working

### ISSUE THREAD

**Issue by ecbrodie** [bulkan/shortcuts-for-trello#12]
Just tried the "scroll to bottom of list" shortcut on my browser and it was not working as expected. I expected it to scroll to the very last card in my list (Trello lane) and highlight that card. However, what it would do is scroll down one "page" of cards in the list, but not go any further, despite me invoking that shortcut again. Scroll to the top works just fine for me. Same with move card to the top.

Note that I had a large Trello lane that I was trying this on, ~30 cards in it. Let me know if you would like any more information about this issue.

**Comment by Orionsg** [comment]
I have assigned Scroll to Bottom/Top of list to Ctrl-B and Ctrl-T, but I cannot get any of them to work. There is no effect what so ever.

**Comment by bulkan** [comment]
@Orionsg the way this extension works is highly reliant on the implementation details of Trello.

If they change it this extension will need to be updated. 

As I don't use Trello heavily like I used to I don't have a need for this extension :) 

You're more than welcome to submit a PR. 

[This is one of the functions that need updating](https://github.com/bulkan/shortcuts-for-trello/blob/develop/src/inject/inject.js#L134)

**Comment by Orionsg** [comment]
@bulkan Thanks for the clarification.

**Comment by ecbrodie** [comment]
@bulkan I don't use this Trello extension anymore, so I have no further reason to keep tracking this issue. I will close. Feel free to reopen if you desire.
