### ISSUE TITLE
Move card shortcut doesn't work

### ISSUE THREAD

**Issue by williamobrien** [bulkan/shortcuts-for-trello#14]
Hello,

Thank you for your great extension. It has been fantastic. Recently though, I've been having an issue. It doesn't matter what combination I try, it won't activate the move shortcut. I have verified that I'm able to get some of the other shortcuts to work, but not the move one. When I look at the inspect tab in Chrome, it is throwing an error in the extension. Here's what I get: 
```
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'click' of null
    at moveCard (chrome-extension://pfkeglfbhfmlnapfjfjfkiipclpmanim/src/inject/inject.js:69:8)
    at routeCommand (chrome-extension://pfkeglfbhfmlnapfjfjfkiipclpmanim/src/inject/inject.js:18:11)
```

Any idea whats going wrong?

Thanks!
William

**Comment by tonytamps** [comment]
I suspect trello has changed the class, element or whatever is used to target the menu and move command.

**Comment by williamobrien** [comment]
I think you're right. I just submitted a pull request fixing the issue.

**Comment by tonytamps** [comment]
This is great! Thanks @williamobrien 
I'll give it a test and get @bulkan to release it.

Appreciate the PR
