### ISSUE TITLE
Options unavailable

### ISSUE THREAD

**Issue by chrisurban** [bulkan/shortcuts-for-trello#21]
Trying to access/update options for extension with chrome://extensions/?options=[id] no longer works with Chrome Version 67.0.3396.87

**Comment by tonytamps** [comment]
This extension has no options. The only config possible is located at `chrome://extensions/shortcuts` where you can set your shortcut keys.

Chrome have the url `chrome://extensions/?id=[id]` but that has nothing to do with extensions and everything to do with chrome.
