### ISSUE TITLE
Shortcut for Copy Card (Like Move Card)

### ISSUE THREAD

**Issue by tdalon** [bulkan/shortcuts-for-trello#5]
It would be nice to have a shortcut also for Copying a Card.
Like for the Move Shortcut it shall open the Copy Card Menu.

**Comment by tonytamps** [comment]
@tdalon you should totally give it a go next time.
It's this easy: https://github.com/bulkan/shortcuts-for-trello/commit/083ff5513c0b4b9b5c4b772bfd18eb3025f1175b

And on that note the new version should be on the web-store in the next few hours.
