### ISSUE TITLE
Add shortcut to move card up and down

### ISSUE THREAD

**Issue by jmgarnier** [bulkan/shortcuts-for-trello#6]
Hi Bulkan,

First, thanks for sharing your extension, I use it every day:)

I'd ❤️  to be able to move cards up & down inside a list using `shift+j` & `shift+k` or another shortcut.

Same kind of thing that `gh` does with issues in milestones.
![image](https://cloud.githubusercontent.com/assets/8051/19592061/64917d60-977a-11e6-930f-35fe75a4fad6.png)

From https://github.com/blog/2206-reorder-issues-within-a-milestone

Is it something you're willing to add? I am up to pay you with paypal or https://www.bountysource.com/ for this feature. We can discuss by e-mail (I've got yours ;)

Cheers,

JM

**Comment by tonytamps** [comment]
Hey @jmgarnier - Thanks for the praise. I also use it every day.
Your request is a good idea, I can see why you (and probably some others) would want it.

At this point though it's worth mentioning that the project is open source and you appear to be able to code, you are very welcome to create a PR and Bulkan will release it.

I'm not saying neither of us will do it but it'll be in our own time.

Side note - I believe Chrome has a limit on the number of keyboard shortcuts an addons can define and we might be approaching or maybe even at it?

**Comment by jmgarnier** [comment]
Thanks for your comment.

I can code, although not so well in `js`. However, I am a very busy dad of 3 small kids so I try to really focus on a few essential projects till they are all older than 3;)

**Comment by carpas** [comment]
+1 for this! Just posted it on this thread...maybe someone volunteers. Thanks for the work so far. 
http://webapps.stackexchange.com/questions/37908/shortcut-key-for-moving-cards-up-or-down-in-trello/101088#101088

By the way, I've read the code and I see the Move Card Up and Move Card Down functions. Could you provide information on whats left to make them work?

Thanks! (+1 Would pay for this)

**Comment by bulkan** [comment]
@carpas this feature was added in this commit https://github.com/bulkan/shortcuts-for-trello/commit/57c736a264ab0818f133ba727ad66a7bf51cb36d by @tonytamps I just need to upload a new version of this extention to chrome web store.

**Comment by bulkan** [comment]
`v1.3.0` is now available on the Chrome Web Store

**Comment by jmgarnier** [comment]
I realised this feature was implemented by accident - sane defaults 😉 - Thank you very much!

If you set up a donation platform, I'll be happy to support you 🌹 🌷 💮

**Comment by tonytamps** [comment]
@jmgarnier Appreciate the offer but we won't be setting anything up 
Enjoy!
